# ==============================================================================
# SonarQube Scanner Configuration
# ==============================================================================

sonar.projectKey=online-boutique-frontend
sonar.projectName=Google Online Boutique - Frontend Service
sonar.projectVersion=1.0.0

sonar.sources=src/frontend
sonar.tests=src/frontend
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/genproto/**,**/vendor/**

sonar.sourceEncoding=UTF-8
sonar.go.coverage.reportPaths=src/frontend/coverage.out
